reference-jdk: &reference-jdk
  'JDK="adopt@1.8"'
reference-os: &reference-os
  'linux'
language: bash
git:
  depth: false
arch:
  - amd64
os:
# OSX dropped due to jabba not installing JDK6 correctly
#  - osx
  - windows
  - *reference-os
dist: bionic
stages:
  - check
  - test
  - deploy
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
  matrix:
    - *reference-jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.9"
    - JDK="adopt@1.10"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@1.12"
    - JDK="adopt-openj9@1.12"
matrix:
  exclude:
    - os: *reference-os
      env: *reference-jdk
jobs:
  include:
    - stage: check
      name: "Compile, check, test on reference JDK"
      os: *reference-os
      env:
        - *reference-jdk
      script:
        - ./gradlew clean check
    - stage: deploy
      name: "Preparation of reports and deployment"
      os: *reference-os
      env:
        - PUBLISH="true"
        - *reference-jdk
        # Signing
        - secure: "V5I3QgUPGXq7frjzDdMonNkPYyMQvqQQmyKkdxCg3BQ7h3bLeb2+iJmHUMy936fsMxXGtYn4D69tyPLbtGr65QLZ788ptKEHv1YRAv/r32dgnP3slcfDZwpGDoLcvODhccM03tpsl+6fZLb0SLu/WiUIfsGWd39+90podcfGqzPy1K5WU5nmkan4b/oshWqXdeGvlJE7NG9Cfsmu2kOdFKBVkVskboM3icgsX+Au39PoAGXF4NZOJjjR3eMllk1yigayzA9pEOBzJukRKAYTOpYvh77xTnehC4ML3aq2zgAXH9zggeL7Hk6p8rtJNm2T7dt+++BjFe2x2TykSOctBU3jg4il+ryZowXtN46uQecfLtrTSrnNLaX6ST1+FlQc0OxjYVtBue9bVp46Chhy+YKJmXswYPJpllCW4QJ8WBZWzafzz42biEouyc4uWfmyyx1wqRJHU6YWu/VfYtTvZSbdlg+IzsnFPjrWR3y5K4Oa5aVS67OxWCJlsSZgFeSOm3MHgqs85uA5G0ZbiWXij5/ExGgTSoY8ksE8Qx6d4dO9ZFEddmZDmqKkNrFqkPwLl+K3JM8jUbjBC8Ky7YXmmzVl4ZQEAwmm4DgvYuFz8CB4CBfa4RJhkCJf4NM9WBUrkETgDMYazP2xI283li7hNM7xHnZKW+W6Y4Aaif+prkU="
        # Central
        - secure: "nfpTiPAgwKjnPqfMWnbDImYeHC/fkgrQktJ3NMxSBzCAXhb9LjMljOkmjztXHtKMWaUtq9+L1dA4eVkHToxlAX0vbNLEhDriHYFaHinQ5fE6KpmzHHxgFwpIrxhmRoYONkgHpu0LaA9QkC8HH9yEqQMfGyGVNhC8HtIxZdHNtvw70ZSk+pxRCTYkkp58A18WUJthSR9LbrnxXscY4NVfFc3aRyWuUr6cmBoRjJ82DhXLT5lbu7P8M47AWB4fovTuqsFFtY285figCZN+7idsAc1mDsDcdFwxrH3tTxtsu7qfluPt8IdY2Dyy3/r+j+7ruuQn+/HJdEu+K1Sf4wgTKOyNSM/iadcoG/gTAE+OpQH4qJuuWmqj1K2SKnvG9IQPt4jRwz7Df2ke1lUjwsVd/SQzqlXhkmZqbfpzlQ78D8P7i7T4/O5mTqLbo6CBNZq+k6fuoi/OE7kbMJ3+JdlcA8ktbAaL9RSdRev7ZoJ4UtfrA8yqTCcSpCKYe0AU+I2U5Ehjsw+Q7n1R79ySikHPgJJVeBIOYzL/UZ177g15Ac9CqsABEA1jrhYCmeKlOftnzz+lGe/9knrmD731DOtRpz7pWvKE4gQTfPOLPsBp+oi4afC4Kb/+D1a0iqu+w/pK3ONOeUGLVuqWY7R9nJXuBGgTJChp6azfoGy3/wc4P70="
        - secure: "LjWnzkJVHNVy+BS5gf8YcgAaxl/cJ6IWUSwAgW9rjXldLaEBX5ymor4+DSZgOv3+B+cxPXqkMYgbtS4C4qDnyYW9xsPF+hColtWN3NN0uf17jjP2SjNvWrsTRyJFps14T2cvYiMwjK81COlWpvaPqZqBiaDi/Kpu2cUxH7KBPF424//il9Ldf9kjB0v97PLbM7WyaMKGJo3uS3uiZQJQUSjbtl0dPxJb8uiJp9Sn31mcHLPjM8Iuc1O+yTwfcAZuzMsZqryh5JYZh9dIL5Du+S+je9F4Qotc1WUfbKfeZIVjsAa5/qvC2rw4uSBfRQEZZf0+GHKWcE0lsg9IFmGptdrn9SumUpsef2AX8PPR0XMjKlXwjGk2pR3QVOC6WDqxP50a+cvRrcrVvSaZFBCuBNUmi2rAGRdHD/bR1j4rb5bKpBdYADp88NaieN8nQUOam+gesuGlhThihILkSqsgtoRlHx7a45+inRpAZ2n4TSkd/CgSOxfhTpf/uPb0I0oMkQLJ7PKVgQhNLiFS6Gky8oAabZmf5FhsPgPNkoVyH+nUFMk8UCmCZj9uca9+PZ5etJnPxR0U3fHOehixMOuGg9JztvHFv9YsaHX58/mFU5xiSF6KuMBSU3lu1Hj6cI5DmtTE5BV8MIjmIQwhOmcI/TpSU7zOCD9JMnWQzz+IuhM="
      install:
        - openssl aes-256-cbc -K $encrypted_817fdb1d0976_key -iv $encrypted_817fdb1d0976_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - ./gradlew sign
      after_success:
        - travis_wait 40 ./gradlew publishAll -x test
before_install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
  - export JAVA6_JDK=$($jabba ls-remote | grep -m1 @1.6)
  - 'echo Selected JDK6: $JAVA6_JDK'
  - '[ ! -z "$JAVA6_JDK" ] || (echo unable to find a JAVA6 version among: && $jabba ls-remote && exit 1)'
  - $jabba install $JAVA6_JDK
  - echo setting ORG_GRADLE_PROJECT_java6Home to $HOME/.jabba/jdk/$JAVA6_JDK
  - export ORG_GRADLE_PROJECT_java6Home=$HOME/.jabba/jdk/$JAVA6_JDK
  - $jabba use $ACTUAL_JDK
script:
  - ./gradlew test
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
